### ISSUE TITLE
Spotlight for eye icon - AB Testing 

### ISSUE THREAD

**Issue by berkeleymobile** [asuc-octo/berkeley-mobile-android#105]
![ab test 2](https://user-images.githubusercontent.com/43453872/47624306-69f11b00-dad8-11e8-9b1f-bd3f39d298e5.png)

**Comment by berkeleymobile** [comment]
Here is the gif: 
![ab_test_2](https://user-images.githubusercontent.com/43453872/47624315-7b3a2780-dad8-11e8-95d7-2598865d57ad.gif)

**Comment by rustielin** [comment]
@berkeleymobile maybe I wasn't clear when we were discussing this during meeting, but I thought we were doing something like this https://github.com/deano2390/MaterialShowcaseView

**Comment by berkeleymobile** [comment]
![ab test](https://user-images.githubusercontent.com/43453872/48216334-48dec480-e339-11e8-8c5e-098b85299f94.png)

**Comment by CourtneyBrousseau** [comment]
The updated mockups and experiment plan are on Nuclino here: https://app.nuclino.com/ASUC-OCTO-Berkeley-Mobile/Berkeley-Mobile/Map-Icons-Discoverability-b75af9df-2680-4a88-b273-b1cd9898754c
