### ISSUE TITLE
UI for library looks off 

### ISSUE THREAD

**Issue by berkeleymobile** [asuc-octo/berkeley-mobile-android#81]
**Describe the bug**
See screenshot below. 

**To Reproduce**
1. Click a specific library. 

**Expected behavior**
Ideally, the hours of the library should be more to the right. 

**Screenshots**
![lib](https://user-images.githubusercontent.com/43453872/45933951-c302e780-bf4b-11e8-8749-3a44bb4f64df.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X]
 - Version [e.g. 8.3]

**Additional context**

**Comment by CourtneyBrousseau** [comment]
I think this can be closed now that it was merged into develop and released in 8.3.3
